"""
Gemini Models Pricing Configuration
Centralized pricing data for all Gemini AI models
"""

GEMINI_MODELS = {
    # 🌟 GEMINI 3 SERIES (Newest - December 2025)
    "gemini-3-pro-preview": {
        "name": "Gemini 3 Pro Preview",
        "series": "3.0",
        "description": "World's best model for multimodal understanding",
        "features": ["Advanced reasoning", "Agentic tasks", "Vibe-coding", "Best multimodal"],
        "use_cases": ["Complex AI agents", "Advanced reasoning", "Cutting-edge apps"],
        "context_window": "1M+ tokens",
        "pricing": {"input": 2.00, "output": 12.00},  # per 1M tokens (includes thinking)
        "quality": 10,
        "speed": 6,
        "status": "preview",
        "free_tier": False,
        "recommended_for": ["ai-agents", "complex-reasoning"],
        "badge": "🌟 WORLD'S BEST"
    },
    "gemini-3-flash-preview": {
        "name": "Gemini 3 Flash Preview",
        "series": "3.0",
        "description": "Most intelligent model built for speed",
        "features": ["Frontier intelligence", "Superior search", "Grounding", "Fast"],
        "use_cases": ["Smart agents", "Fast reasoning", "Production apps"],
        "context_window": "1M tokens",
        "pricing": {"input": 0.50, "output": 3.00},
        "quality": 10,
        "speed": 9,
        "status": "preview",
        "free_tier": True,
        "recommended_for": ["intelligent-speed"],
        "badge": "⚡ FASTEST INTELLIGENCE"
    },
    
    # ⚡ GEMINI 2.5 SERIES (Stable - September 2025)
    "gemini-2.5-flash": {
        "name": "Gemini 2.5 Flash",
        "series": "2.5",
        "description": "Best price-performance with hybrid reasoning",
        "features": ["Thinking budgets", "Fast processing", "1M context", "Agentic workflows"],
        "use_cases": ["PDF conversion", "Large scale processing", "High volume tasks"],
        "context_window": "1M tokens",
        "pricing": {"input": 0.30, "output": 2.50},
        "quality": 9,
        "speed": 9,
        "status": "stable",
        "free_tier": True,
        "recommended_for": ["pdf-conversion", "production", "default"],
        "badge": "⭐ RECOMMENDED"
    },
    "gemini-2.5-flash-preview-09-2025": {
        "name": "Gemini 2.5 Flash Preview",
        "series": "2.5",
        "description": "Latest preview with newest improvements",
        "features": ["Latest features", "Thinking enabled", "1M context"],
        "use_cases": ["Testing new features", "Beta testing", "Advanced users"],
        "context_window": "1M tokens",
        "pricing": {"input": 0.30, "output": 2.50},
        "quality": 9,
        "speed": 9,
        "status": "preview",
        "free_tier": True,
        "recommended_for": ["beta-testing"],
    },
    "gemini-2.5-flash-lite": {
        "name": "Gemini 2.5 Flash-Lite",
        "series": "2.5",
        "description": "Most cost-effective for scale",
        "features": ["Ultra-fast", "80% cheaper", "High throughput", "1M context"],
        "use_cases": ["Simple text extraction", "High volume", "Budget-conscious"],
        "context_window": "1M tokens",
        "pricing": {"input": 0.10, "output": 0.40},
        "quality": 8,
        "speed": 10,
        "status": "stable",
        "free_tier": True,
        "recommended_for": ["budget", "high-volume"],
        "badge": "💰 CHEAPEST"
    },
    "gemini-2.5-flash-lite-preview-09-2025": {
        "name": "Gemini 2.5 Flash-Lite Preview",
        "series": "2.5",
        "description": "Latest lite model - cost-efficient, high quality",
        "features": ["Cost optimization", "High throughput", "Quality improvements"],
        "use_cases": ["Budget production", "High scale", "Fast processing"],
        "context_window": "1M tokens",
        "pricing": {"input": 0.10, "output": 0.40},
        "quality": 8,
        "speed": 10,
        "status": "preview",
        "free_tier": True,
        "recommended_for": ["cost-efficiency"],
    },
    "gemini-2.5-pro": {
        "name": "Gemini 2.5 Pro",
        "series": "2.5",
        "description": "Advanced thinking for complex problems",
        "features": ["Advanced reasoning", "Long context", "Code/math/STEM expert", "2M context"],
        "use_cases": ["Complex research", "Large codebases", "Scientific problems"],
        "context_window": "2M tokens",
        "pricing": {"input": 1.25, "output": 10.00},
        "quality": 10,
        "speed": 7,
        "status": "stable",
        "free_tier": True,
        "recommended_for": ["complex-reasoning", "research"],
        "badge": "🎯 HIGHEST QUALITY"
    },
    
    # 🔧 GEMINI 2.0 SERIES (Previous Generation - October 2024)
    "gemini-2.0-flash": {
        "name": "Gemini 2.0 Flash",
        "series": "2.0",
        "description": "Second generation workhorse model",
        "features": ["1M context", "Balanced performance", "Multimodal", "Agent-ready"],
        "use_cases": ["General purpose", "Production apps", "Balanced workloads"],
        "context_window": "1M tokens",
        "pricing": {"input": 0.10, "output": 0.40},
        "quality": 8,
        "speed": 9,
        "status": "stable",
        "free_tier": True,
        "recommended_for": ["general-purpose"],
    },
    "gemini-2.0-flash-exp": {
        "name": "Gemini 2.0 Flash Experimental",
        "series": "2.0",
        "description": "Experimental version with latest features",
        "features": ["Experimental features", "1M context", "Fast", "May change"],
        "use_cases": ["Testing", "Experiments", "Non-production"],
        "context_window": "1M tokens",
        "pricing": {"input": 0.075, "output": 0.30},
        "quality": 8,
        "speed": 9,
        "status": "experimental",
        "free_tier": True,
        "recommended_for": ["testing"],
    },
    "gemini-2.0-flash-lite": {
        "name": "Gemini 2.0 Flash-Lite",
        "series": "2.0",
        "description": "Second gen small workhorse",
        "features": ["1M context", "Cost-effective", "High throughput"],
        "use_cases": ["High volume", "Simple tasks", "Budget apps"],
        "context_window": "1M tokens",
        "pricing": {"input": 0.075, "output": 0.30},
        "quality": 7,
        "speed": 10,
        "status": "stable",
        "free_tier": True,
        "recommended_for": ["simple-tasks"],
    },
}

# Default model recommendation
DEFAULT_GEMINI_MODEL = "gemini-2.5-flash"
